import Head from "next/head";
import GenreList from "../components/GenreList";
import MoviesList from "../components/MoviesList";
import Navbar from "../components/Navbar";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>PS - Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <Navbar />
      {/* Genre List*/}
      <GenreList />
      {/* Movies list */}
      {results && <MoviesList moviesList={results} />}
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
